version: "3.8"

services:
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
