apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app
  labels:
    app: ci-cd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
      - name: ci-cd-app-container
        image: ubuntu:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: "/health"
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20