apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alert-rules.yaml: |
    groups:
    - name: example
      rules:
      - alert: HighCPUUsage
        expr: node_cpu_seconds_total > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage Detected"
          description: "CPU usage is above 80% for more than 2 minutes."
