name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run Tests
        run: pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v4.2.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "your-heroku-app"
          heroku_email: "nicholas.clark@outlook.com"
